export { NativeModule } from './native.module';

// export { AppPlugin } from './app';
// export { BadgePlugin } from './badge';
// export { BarcodePlugin } from './barcode';
// export { BackgroundModePlugin } from './background-mode';
// export { CapacitorKeepScreenOnPlugin } from './keep-screen-on';
export { DevicePlugin } from './device';
// // export { ElectronPlugin } from './electron';
// export { FaceIdPlugin, FaceIdResponse } from './face-id';
// export { FileSystemPlugin, FileSystemPluginDirectory, FileExistsResult, DownloadFileResult } from './file-system';
// export { GeolocationPlugin } from './geolocation';
// export { InAppBrowserPlugin } from './in-app-browser';
// export { KeyboardPlugin } from './keyboard';
// export { LocalNotificationPlugin } from './local-notification';
// export { MediaPlugin } from './media';
// // export { MotionPlugin } from './motion';
// // export { NavigationBarPlugin } from './navigation-bar';
// export { NavigationBarColorPlugin } from './navigation-bar-color';
// export { NetworkPlugin } from './network';
// export { SpeechRecognitionPlugin } from './speech-recognition';
// export { SplashScreenPlugin } from './splash-screen';
// export { StatusBarPlugin } from './status-bar';
// export { StoragePlugin } from './storage';
