export { CoreNativeModule } from './native.module';

export { AppPlugin } from './app';
export { AppLauncherPlugin } from './app-launcher';
export { BadgePlugin } from './badge';
// export { BarcodePlugin } from './barcode';
export { BiometricPlugin } from './biometric';
export { CapacitorKeepScreenOnPlugin } from './keep-screen-on';
export { DevicePlugin } from './device';
export { FileSystemPlugin, FileSystemPluginDirectory, FileExistsResult, DownloadFileResult } from './file-system';
export { GeolocationPlugin } from './geolocation';
export { InAppBrowserPlugin } from './in-app-browser';
export { KeyboardPlugin } from './keyboard';
export { LocalNotificationPlugin } from './local-notification';
export { MediaPlugin } from './media';
// // export { MotionPlugin } from './motion';
export { NetworkPlugin } from './network';
export { SpeechRecognitionPlugin } from './speech-recognition';
export { SplashScreenPlugin } from './splash-screen';
export { StatusBarPlugin } from './status-bar';
export { StoragePlugin } from './storage';
export { TextToSpeechPlugin } from './text-to-speech';
export { TextZoomPlugin } from './text-zoom';
